spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 2000
  datasource:
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
  target-datasource:
    url: '${MASTER_DB_URL}'
    username: '${MASTER_DB_USERNAME}'
    password: '${MASTER_DB_PASSWORD}'